export declare const str: (value?: string) => object;
export declare const bool: (value?: number | boolean | boolean[]) => object;
export declare const float: (value?: number) => object;
export declare const double: (value?: number) => object;
export declare const bin: (value?: string) => object;
export declare const time: (value?: Date) => object;
export declare const ip4: (value?: string) => object;
export declare const s8: (value?: number | number[]) => object;
export declare const s16: (value?: number | number[]) => object;
export declare const s32: (value?: number | number[]) => object;
export declare const s64: (value?: number | number[]) => object;
export declare const u8: (value?: number | number[]) => object;
export declare const u16: (value?: number | number[]) => object;
export declare const u32: (value?: number | number[]) => object;
export declare const u64: (value?: number | number[]) => object;
//# sourceMappingURL=index.d.ts.map